-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2SiNbbV+zytFlg1n
Roj+sQo1X28HEhVu868RZPP2FeagCgYIKoZIzj0DAQehRANCAASJM9BndViL4ZNL
udBXAu2psruqiniovqYma5TvieHfSGeLMcMyWtBBhgVUbMBUKNDdiSjgVwU5uZYW
792wtod4
-----END PRIVATE KEY-----